### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aytacmalkoc** [bchiang7/halcyon-site#17]
hi, what is the license type? You mentioned that it is open source in the field of quick start. I think you are sharing with MIT license but I wanted to ask anyway :)

**Comment by bchiang7** [comment]
Hi @aytacmalkoc, there's mention of a MIT license in the readme because I used the [Gatsby default starter](https://github.com/gatsbyjs/gatsby-starter-default) to quickly spin up this site 😅 

I don't currently have a license for this repo, but if I added one, it would probably be MIT
